### ISSUE TITLE
PROJECT API KEY - Update l2 packet api client to support upstream api changes for switching to mixed hybrid 

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#171] opened 2019-01-31 01:07 UTC
Issue:  The packet l2 client does not seem to change a Packet machines network type from Layer-3 to Mixed-Hybrid.  

The client is being run from the [ansible role](https://github.com/cncf/cnfs/tree/master/comparison/ansible/roles/packet_l2).  A "changed" response is returned from Ansible.  VLANs are created if they do not exist or existing VLANs are used as exepected.  The network type of a Machine does not get changed though.

Acceptance Criteria:
- [ ] A machines network type should change from Layer-3 to Hybrid when the client runs against that machine
   - [ ] client running directly from cli works as expected
   - [ ] Using the [packet_l2 ansible role](https://github.com/cncf/cnfs/tree/master/comparison/ansible/roles/packet_l2) works as expected

**Comment by denverwilliams** [comment] 2019-01-31 21:06
The problem seems to be with project level api keys no longer having the necessary authorization to make host networking modifications. 
After switching to personal/profile level api keys we can successfully make network level changes again.

Steps to reproduce:

Clone the CNFs repo and cd to the packet_l2 client
```
git@github.com:cncf/cnfs.git
cd cnfs/tools/packet_api
```
Set the Following ENV vars
```
export PACKET_API_URL="api.packet.net"
export PACKET_API_TOKEN="your-project-level-api-key"
```

Run the dis-bond interface command against a server:
```
ruby ./l2_packet_networking.rb --server yourserverhostname --disbond-interface eth1 --project-name='CNCF CNFs' -v
```

Debug log:
```
"bond_port: {\"id\"=>\"5d972507-0f89-4f20-b671-f1fe8f4cecdf\", \"type\"=>\"NetworkPort\", \"name\"=>\"eth1\", \"data\"=>{\"bonded\"=>true, \"mac\"=>\"ec:0d:9a:ca:69:15\"}, \"bond\"=>{\"id\"=>\"a8c02d80-75d9-4d59-bee3-db4b63d83df4\", \"name\"=>\"bond0\"}, \"native_virtual_network\"=>nil, \"hardware\"=>{\"href\"=>\"/hardware/2af4d378-c243-4cbf-9098-c4d4422f04ec\"}, \"virtual_networks\"=>[], \"connected_port\"=>{\"href\"=>\"/ports/46403649-97a6-43da-84d0-cfde7fc4ec71\"}, \"href\"=>\"/ports/5d972507-0f89-4f20-b671-f1fe8f4cecdf\"}"
"parsed bond_response: {\"errors\"=>[\"Access denied for the current authentication token\"]}"
failure
```

**Comment by vielmetti** [comment] 2019-01-31 21:46
XKEE-1682-NFQZ is the @packethost ticket number for this, and I've been in touch with engineering to see what might have triggered this.

**Comment by vielmetti** [comment] 2019-02-08 23:44
Thank you for the debug log, that is proving useful to isolate the issue.

**Comment by taylor** [comment] 2019-02-11 15:33
On Feb 11th, @vielmetti said:
> Our ticket regarding “Project API keys not allowed to use /ports” is in progress. Typically this might mean a release this week, but not guaranteed. I’ll advise when the ticket is reported closed.

Sounds great.  Thanks for the update @vielmetti.

Let us know if there is anything we can help with.

**Comment by taylor** [comment] 2019-04-11 20:22
Project key did not work during the week of April 1st

**Comment by vielmetti** [comment] 2019-05-17 03:26
@Taylor - the issue internal to Packet that is tracking this issue is marked as "done". It's still open here. At your convenience if you can help test or retest this and see what the real state of affairs is, I'll confirm or reopen that issue.

**Comment by linkous8** [comment] 2019-05-21 15:25
I can confirm project keys are able to make network changes on the packet hosts as I have done all my testing with a project key (specifically for those with project access, fredkey1)

**Comment by vielmetti** [comment] 2019-05-21 16:34
Thanks @linkous8  - based on that I think this issue can be closed @taylor

**Closed** 2020-01-31 00:25 UTC
Labels: bug, packet.net
