### ISSUE TITLE
TBD: VPP vSwitch in a POD for K8s w/Mellanox NICs

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#212] opened 2019-03-25 15:54 UTC

**Comment by michaelspedersen** [comment] 2019-04-23 16:12
Ongoing, currently looking at solution using rdma-core instead of OFED software from Mellanox.

**Comment by michaelspedersen** [comment] 2019-04-25 15:00
Duplicate of https://github.com/cncf/cnf-testbed/issues/220 - Closing this one

**Closed by michaelspedersen** 2019-04-25 15:00 UTC
