### ISSUE TITLE
Update traffic generator to work with the Packet m2.xlarge Mellanox instance

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#190] opened 2019-02-20 23:31 UTC
Issue: deployment code for traffic generator not functioning with the mellanox servers

@michaelspedersen saw that the nickjj docker instance is failing with an error that seems to be related to connectivity - (not yet validated from the server)

Task
---
- [x] deploy new packet generator in the same facility as the openstack cluster
- [x] set packet generator to be in same vlan
- [x] investigate connectivity issue

TBD

**Comment by taylor** [comment] 2019-02-20 23:37
TBD post MWC, add a smoke test to run after deploy.  Eg.
- deploy linux system
- configure linux system to be on same vlan as packet generator
- configure linux system to respond to ping and ARP requests
- run ping and arping from traffic generator to test linux system

**Comment by taylor** [comment] 2019-02-21 17:32
Issue: how to pass server list for packet l2 setup

The packet generator [deploy script](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/packet_generator/deploy_packet_generator.sh#L40-L60) nor Terraform passes the server IP/hostname for packet layer-2 role.  

Need to find a solution to pass the server list or optionally look at updating the role.

Current examples:
- [Using ansible playbook directly](https://github.com/cncf/cnf-testbed/blob/b9b1db59f6474544a22c4c4570cd11aab86d96bc/comparison/kubecon18-chained_nf_test/docs/dev.mkd#L33)
- [Setting env from Terraform inventory file](https://github.com/cncf/cnf-testbed/blob/90fc53336ca98d08fc0f318fe52dae0d8e2da19d/tools/deploy_openstack_cluster.sh#L38)

**Comment by robertstarmer** [comment] 2019-02-21 18:36
@taylor I have been creating a separate ansible inventory as a part of the initial terraform build via ansible.  And it's one of the reasons why there are two separate ansible scripts (one is for infrastructure specific setup tasks, and one is for the chef and other tools deployments).

The issue is that while Terraform will run ansible as it's installation script, it runs it individually for each host built, rather than after all hosts are created.  So the openstack process creates an "all" group initially to capture per node information:

https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/openstack_infra_setup.yml#L95-L98

(and we could add ansible_hostname as a variable to that list to get not only the host IP which is what inventory_hostname returns but the actual instance hostname as well)

Then I get an ordered list by parsing the tfstate file and add that to the inventory before running ansible again for the Chef install, as I need to know which host is which, and not just which host built first.

https://github.com/cncf/cnf-testbed/blob/master/tools/deploy_openstack_cluster.sh#L37

And then I re-run ansible but with the chef playbook, which is also where I'm running the packet_l2 role, so the IP (and with a small modification hostname) can be available as Ansible variables.

**Comment by lixuna** [comment] 2019-08-12 20:42
completed -- traffic generator works with m2.xlarge. closing ticket

**Closed by lixuna** 2019-08-12 20:42 UTC
Labels: bug
